#ifndef __INTERNAL_FLASH_H
#define __INTERNAL_FLASH_H



#define  FLASH_BKP_DATA  0xA6A6
#define  FLASH_WIFI_DATA 0xA7A7
#define  ID_KEY_SUCCESS  0XA2A2 //成功导入激活码后，写入内存变量作为标志




//开机默认配置参数，不再更改




#define  LOGIND_HEAD_ADDRESS     (0x08000000+118*1024) 
#define  LOGIN_1_H    (LOGIND_HEAD_ADDRESS+4)
#define  LOGIN_1_L   (LOGIND_HEAD_ADDRESS+8)
#define  LOGIN_1_ACCESS   (LOGIND_HEAD_ADDRESS+12)


#define  TARGET_HEAD_ADDRESS  (0x08000000+2*1024*100) //将数据保存在第120K开始的地方






#define  CHECK_FLASH_ADDRESS		(TARGET_HEAD_ADDRESS+12)
#define  CHECK_WIFI_ADDRESS (TARGET_HEAD_ADDRESS+16)

#define    SYS_LOCK_SET_ADDRESS  (TARGET_HEAD_ADDRESS+20)
#define   WIFI_LOCK_SET_ADDRESS (TARGET_HEAD_ADDRESS+24)

#define   WIFI_LOCK_YEAR_ADDRESS (TARGET_HEAD_ADDRESS + 28)
#define   WIFI_LOCK_MONTH_ADDRESS (TARGET_HEAD_ADDRESS + 32)
#define   WIFI_LOCK_DAY_ADDRESS (TARGET_HEAD_ADDRESS + 36)




#define  ZHUAN_HUAN_TEMPERATURE   (TARGET_HEAD_ADDRESS + 40)
#define  AUTO_STOP_PRESSURE_ADDRESS   (TARGET_HEAD_ADDRESS+44)
#define    AUTO_START_PRESSURE_ADDRESS  (TARGET_HEAD_ADDRESS+48)



//用于保存管理员设置参数
#define  ADMIN_HEAD_ADDRESS  (0x08000000+ 110*1024) 
#define  FIRST_BLOW_ADDRESS   (ADMIN_HEAD_ADDRESS)
#define  LAST_BLOW_ADDRESS   (ADMIN_HEAD_ADDRESS+4)
#define  WEN_HUO_ADDRESS   (ADMIN_HEAD_ADDRESS+8)
#define  STOP_TEMPERATURE   (ADMIN_HEAD_ADDRESS+12)

#define  DIAN_HUO_POWER_ADDRESS   (ADMIN_HEAD_ADDRESS+16) 

#define  ADMIN_WORK_DAY_ADDRESS   (ADMIN_HEAD_ADDRESS+20)
#define  ADMIN_SAVE_YEAR_ADDRESS   (ADMIN_HEAD_ADDRESS+24)
#define  ADMIN_SAVE_MONTH_ADDRESS   (ADMIN_HEAD_ADDRESS+28)
#define  ADMIN_SAVE_DAY_ADDRESS   (ADMIN_HEAD_ADDRESS+32)
#define   MAX_WORK_POWER_ADDRESS   (ADMIN_HEAD_ADDRESS+36)  //最大可运行功率

#define   FAN_SPEED_CHECK_ADDRESS   (ADMIN_HEAD_ADDRESS+40) //是否检测风速地址
#define   FAN_SPEED_VALUE_ADDRESS   (ADMIN_HEAD_ADDRESS+44) //风机最大风速地址
#define   FAN_FIRE_VALUE_ADDRESS   (ADMIN_HEAD_ADDRESS+48)//点火转速检测地址
#define   DANGER_SMOKE_VALUE_ADDRESS   (ADMIN_HEAD_ADDRESS+52)//排烟温度报警值设置地址
#define   AUTO_BLOW_SET_ADDRESS   (ADMIN_HEAD_ADDRESS+56)//自动排污设置地址
#define	  FIRE_MODE_SET_ADDRESS 	(ADMIN_HEAD_ADDRESS+60)//引火功能设置地址
#define   MODBUS_ADDRESS_SET_ADDRESS (ADMIN_HEAD_ADDRESS+64)//ModBus设置地址

#define   MODBUS_FUNCTION_ADDRESS (ADMIN_HEAD_ADDRESS+68)
#define   MODBUS_ADDRESS_ADDRESS (ADMIN_HEAD_ADDRESS+72)

#define   SUPPLY_MAX_TIME_ADDRESS (ADMIN_HEAD_ADDRESS+76)//补水超时报警值保存地址

#define	DEVICE_MAX_PRESSURE_SET_ADDRESS (ADMIN_HEAD_ADDRESS+80) //额定蒸汽压力设置保存地址
#define	ACCESS_DATA_MODE_SET_ADDRESS (ADMIN_HEAD_ADDRESS+84)  //远程数据获取模式地址



#define   PAIWU_STAGE1TIME_ADDRESS (ADMIN_HEAD_ADDRESS+88)
#define   PAIWU_STAGE1_OPENFLAG_ADDRESS (ADMIN_HEAD_ADDRESS+92)
#define   PAIWU_STAGE2TIME_ADDRESS (ADMIN_HEAD_ADDRESS+96)
#define   PAIWU_STAGE2_OPENFLAG_ADDRESS (ADMIN_HEAD_ADDRESS+100)


#define   BALANCE_BIGPOWER_ADDRESS (ADMIN_HEAD_ADDRESS+112)
#define   BALANCE_SMALLPOWER_ADDRESS (ADMIN_HEAD_ADDRESS+116)
#define   BALANCE_BIGTIME_ADDRESS (ADMIN_HEAD_ADDRESS+120)
#define   BALANCE_SMALLTIME_ADDRESS (ADMIN_HEAD_ADDRESS+124)

#define   FIRE_DETECT_MODE_ADDRESS (ADMIN_HEAD_ADDRESS+128)
#define   LOGIN_CONTROL_MODE_ADDRESS (ADMIN_HEAD_ADDRESS+132)
#define   SPECIAL_SECS_ADDRESS (ADMIN_HEAD_ADDRESS+136)
#define   BENTI_WENDU_PROTECT_ADDRESS (ADMIN_HEAD_ADDRESS+140)
#define   STEAM_WENDU_PROTECT_ADDRESS (ADMIN_HEAD_ADDRESS+144)
#define   WENDU_PROTECT_ADDRESS (ADMIN_HEAD_ADDRESS+148)
#define   SAFETY_PROTECT_ADDRESS (ADMIN_HEAD_ADDRESS+152)



#define   WATER_BIANPIN_ADDRESS (ADMIN_HEAD_ADDRESS+156)
#define   WATER_MAXPERCENT_ADDRESS (ADMIN_HEAD_ADDRESS+160)


#define   LianXu_PaiWu_Enabled_ADDRESS (ADMIN_HEAD_ADDRESS + 164)
#define   LianXu_PaiWu_DelayTime_ADDRESS (ADMIN_HEAD_ADDRESS + 168)
#define   LianXu_PaiWu_OpenSecs_ADDRESS (ADMIN_HEAD_ADDRESS + 172)
#define   Device_Style_Choice_ADDRESS (ADMIN_HEAD_ADDRESS + 176)


#define   FAN_PULSE_RPM_ADDRESS (ADMIN_HEAD_ADDRESS + 180)

#define   CHAYA_WATER_ENABLED (ADMIN_HEAD_ADDRESS + 184)
#define   CHAYA_WATERLOW_SET (ADMIN_HEAD_ADDRESS + 188)
#define   CHAYA_WATERMID_SET (ADMIN_HEAD_ADDRESS + 192)
#define   CHAYA_WATERHIGH_SET (ADMIN_HEAD_ADDRESS + 196)






//运行中持续更改参数
#define  SECOND_HEAD_ADDRESS  (0x08000000+122*1024) 

#define	 SYS_WORK_TIME_ADDRESS  (SECOND_HEAD_ADDRESS+4)

#define	 A2_KEY_POWER_ADDRESS  (SECOND_HEAD_ADDRESS+8)
#define	 A2_FIRE_POWER_ADDRESS  (SECOND_HEAD_ADDRESS+12)
#define	 A2_MAX_POWER_ADDRESS  (SECOND_HEAD_ADDRESS+16)
#define	 A2_SMOKE_PROTECT_ADDRESS  (SECOND_HEAD_ADDRESS+20)
#define	 A2_INSIDESMOKE_PROTECT_ADDRESS  (SECOND_HEAD_ADDRESS+24)


#define	 A3_KEY_POWER_ADDRESS  (SECOND_HEAD_ADDRESS+28)
#define	 A3_FIRE_POWER_ADDRESS  (SECOND_HEAD_ADDRESS+32)
#define	 A3_MAX_POWER_ADDRESS  (SECOND_HEAD_ADDRESS+36)
#define	 A3_SMOKE_PROTECT_ADDRESS  (SECOND_HEAD_ADDRESS+40)
#define	 A3_INSIDESMOKE_PROTECT_ADDRESS  (SECOND_HEAD_ADDRESS+44)

#define	 A1_KEY_POWER_ADDRESS  (SECOND_HEAD_ADDRESS+48)








//配置一次，不再更改










//将系统设置参数写在内部FLASH中保存

void Write_Internal_Flash(void);
void Write_Admin_Flash(void);



void Write_Second_Flash(void);






#endif
